export const SUBMIT_COURSE_REQUEST = 'newCourseReducer/SUBMIT_COURSE_REQUEST'
export const SUBMIT_COURSE_SUCCESS = 'newCourseReducer/SUBMIT_COURSE_SUCCESS'
export const SUBMIT_COURSE_FAILED = 'newCourseReducer/SUBMIT_COURSE_FAILED'
