export const SUBMIT_CATEGORY_REQUEST = 'newCourseReducer/SUBMIT_CATEGORY_REQUEST'
export const SUBMIT_CATEGORY_SUCCESS = 'newCourseReducer/SUBMIT_CATEGORY_SUCCESS'
export const SUBMIT_CATEGORY_FAILED = 'newCourseReducer/SUBMIT_CATEGORY_FAILED'
